version: 2
updates:
  # Enable version updates for npm
  # Skipping dependency version updates: Dependabot is enabled with Vulnerability Alerts, which is really when an update needs to run
  # - package-ecosystem: 'npm'
  #   # Look for `package.json` and `lock` files in the `root` directory
  #   directory: '/'
  #   # Check the npm registry for updates every week
  #   schedule:
  #     interval: 'monthly'
      
  # Enable version updates for actions
  - package-ecosystem: 'github-actions'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    # Check the npm registry for updates every week
    schedule:
      interval: 'monthly'

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
