name: Publishing the action to the marketplace

on:   
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

# Declare default GITHUB_TOKEN permissions as read only.
permissions: read-all
 
jobs:
  test-local-action:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - uses: ./
        name: Load used actions as a test
        with: 
          PAT: ${{ secrets.PAT }}
          user: rajbos
        id: load-actions
            
      - name: Upload result file as artefact
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
        with: 
          name: actions
          path: ${{ steps.load-actions.outputs.actions-file-path }}
    
  publish:
    needs: test-local-action
    runs-on: ubuntu-latest
    steps:
      # get code
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      # build it
      - run: |
          npm ci
          npm run all

      # get tag for this release
      - name: Get tag value
        id: tag
        uses: devops-actions/action-get-tag@19f393df16cb09284484fb49bf678004bf50896a # v1.0.1

      # publish a release with the build assets
      - uses: rajbos-actions/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
        id: publish
        with:
          name: Release ${{ steps.tag.outputs.tag }}
          tag_name: ${{ github.ref }}
          body: Release ${{ steps.tag.outputs.tag }} is available now
          files: ./dist/main.js
          token: ${{ secrets.PAT }}

      - run: |
          echo "$url"
        env:
          url: ${{ steps.publish.outputs.url }}

      - uses: rajbos-actions/slack@ed1309ab9862e57e9e583e51c7889486b9a00b0f # v2.0.0
        with: 
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
