name: Publishing the action to the marketplace

on:   
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

# Declare default GITHUB_TOKEN permissions as read only.
permissions: read-all
 
jobs:
  test-local-action:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

      - uses: ./
        name: Load used actions
        with: 
          PAT: ${{ secrets.PAT }}
          user: rajbos
        id: load-actions

      - uses: devops-actions/json-to-file@f4dfed5916186ad86a993f72d3d8182e543598ea # v1.0.1
        with: 
          json: ${{ steps.load-actions.outputs.actions }}
          filename: actions.json
            
      - name: Upload result file as artefact
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb # v3.1.1
        with: 
          name: actions
          path: actions.json
    
  publish:
    needs: test-local-action
    runs-on: ubuntu-latest
    steps:
      # get code
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

      # build it
      - run: |
          npm ci
          npm run all

      # get tag for this release
      - name: Get tag value
        id: tag
        uses: rajbos-actions/action-get-tag@12319896edaa290b27558e34a177804e9b8d077b # v1   

      # publish a release with the build assets
      - uses: rajbos-actions/action-gh-release@6034af24fba4e5a8e975aaa6056554efe4c794d0 # v1
        id: publish
        with:
          name: Release ${{ steps.tag.outputs.tag }}
          tag_name: ${{ github.ref }}
          body: Release ${{ steps.tag.outputs.tag }} is available now
          files: ./dist/main.js
          token: ${{ secrets.PAT }}

      - run: |
          echo "$url"
        env:
          url: ${{ steps.publish.outputs.url }}

      - uses: rajbos-actions/slack@e4e71685b9b239384b0f676a63c32367f59c2522 # v1.2.2
        with: 
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
