name: Repo SemVer check
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  semver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4
        with:
          fetch-depth: 0 # needed to get all tags
      
      - uses: jessehouwing/actions-semver-checker@3cb8b94e8a9f14b89c86702e5c8c7c3d95559c5e # v1
