name: Testing the action

on: 
  push:

  workflow_dispatch:

# declare default GITHUB_TOKEN permissions as read only.
permissions: read-all
    
jobs:
  test-load-from-user: # test the action for the user space
    name: User space
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      # make sure we have a new build, in case the dist folder was not updated
      - name: Compile with NPM
        run: | 
          npm ci
          npm run all

      # run the test
      - uses: ./
        name: Load available actions
        with: 
          PAT: ${{ secrets.PAT }} 
          user: rajbos
        id: load-actions 

      # check if the result file is not empty
      - name: Check if the result file is not empty
        run: | 
          if [ ! -s "${{ steps.load-actions.outputs.actions-file-path }}" ]; then
            echo "The result file is empty" | tee "$GITHUB_STEP_SUMMARY"
            exit 1
          fi

          ls -la

      - name: Check if the result file has actions in it
        run: |
          # check if the file has actions in it 
          if [ "$(jq '.actions | length' "${{ steps.load-actions.outputs.actions-file-path }}")" -eq 0 ]; then
            echo "The result file does not contain any actions" | tee "$GITHUB_STEP_SUMMARY"
            exit 1
          fi

      - name: Check if the results file has dubplicate actions
        run: |
          # check if the file has actions in it 
          echo "Actions array length = $(jq '.actions | length' "${{ steps.load-actions.outputs.actions-file-path }}")"
          echo "Unique actions by name = $(jq '.actions | unique_by({name, repo}) | length' "${{ steps.load-actions.outputs.actions-file-path }}")"
          if [ "$(jq '.actions | length' "${{ steps.load-actions.outputs.actions-file-path }}")" -ne "$(jq '.actions | unique_by({name, repo}) | length' "${{ steps.load-actions.outputs.actions-file-path }}")" ]; then
            echo "The result file contains duplicate actions" | tee "$GITHUB_STEP_SUMMARY"
            exit 1
          fi

      # upload the second result file as an artefact 
      - name: Upload result file as artefact
        if: always()
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with: 
          name: actions-user
          path: ${{ steps.load-actions.outputs.actions-file-path }}

      # run the test with a different filename
      - uses: ./
        name: Load available actions
        with: 
          PAT: ${{ secrets.PAT }} 
          user: rajbos
          outputFilename: actions-second-run.json
        id: load-actions-second-run

      # check if the second result file is not empty
      - name: Check if the second result file is not empty
        run: | 
          if [ ! -s '${{ steps.load-actions-second-run.outputs.actions-file-path }}' ]; then
            echo "The result file is empty" | tee "$GITHUB_STEP_SUMMARY"
            exit 1
          fi

      # upload the second result file as an artefact
      - name: Upload result file as artefact
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with: 
          name: actions-user
          path: ${{ steps.load-actions-second-run.outputs.actions-file-path }}
      
      # validate that the two files have different names
      - name: Validate that the two files have different names
        run: | 
          if [ ${{ steps.load-actions.outputs.actions-file-path }} == ${{ steps.load-actions-second-run.outputs.actions-file-path }} ]; then
            echo "The two files have the same name, this is not good" | tee "$GITHUB_STEP_SUMMARY"
            exit 1
          else
            echo "The two files have different names, this is good" | tee "$GITHUB_STEP_SUMMARY"
          fi
  
  test-load-from-organization-with-forks: # test the action for the organization space
    #needs: test-load-from-user
    runs-on: ubuntu-latest
    concurrency: single-run
    name: Org with forks
    steps: 
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      # make sure we have a new build, in case the dist folder was not updated
      - name: Compile with NPM
        run: | 
          npm ci
          npm run all

      # run the test
      - uses: ./
        name: Load available actions
        with: 
          PAT: ${{ secrets.PAT }}
          organization: rajbos-actions
        id: load-actions

      # check if the result file is not empty
      - name: Check if the result file is not empty
        run: | 
          if [ ! -s "${{ steps.load-actions.outputs.actions-file-path }}" ]; then
            echo "The result file is empty" | tee "$GITHUB_STEP_SUMMARY"
            exit 1
          fi

      - name: Check if the result file has actions in it        
        run: | 
          # check if the file has actions in it 
          if [ "$(jq '.actions | length' "${{ steps.load-actions.outputs.actions-file-path }}")" -eq 0 ]; then
            echo "The result file does not contain any actions" | tee "$GITHUB_STEP_SUMMARY"
            exit 1
          fi
            
      - name: Upload result file as artefact
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        if: always()
        with: 
          name: actions-organization-with-forks
          path: ${{ steps.load-actions.outputs.actions-file-path }}
    
  test-load-from-organization: # test the action for the organization space
    name: Org without forks
    runs-on: ubuntu-latest
    needs: test-load-from-organization-with-forks
    concurrency: single-run
    if: always()
    steps: 
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      # make sure we have a new build, in case the dist folder was not updated
      - name: Compile with NPM
        run: | 
          npm ci
          npm run all
      # run the test
      - uses: ./
        name: Load available actions
        with: 
          PAT: ${{ secrets.PAT }}
          organization: actions
        id: load-actions

      # check if the result file is not empty
      - name: Check if the result file is not empty
        run: | 
          if [ ! -s '${{ steps.load-actions.outputs.actions-file-path }}' ]; then
            echo "The result file is empty"
            exit 1
          fi

      - name: Check if the result file has actions in it
        run: |
          # check if the file has actions in it 
          if [ "$(jq ".actions | length" "${{ steps.load-actions.outputs.actions-file-path }}")" -eq 0 ]; then
            echo "The result file does not contain any actions" | tee "$GITHUB_STEP_SUMMARY"
            exit 1
          fi
            
      - name: Upload result file as artefact
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with: 
          name: actions-organization
          path: ${{ steps.load-actions.outputs.actions-file-path }}

