name: Testing the action

on: 
  push:

  workflow_dispatch:

# Declare default GITHUB_TOKEN permissions as read only.
permissions: read-all
    
jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # don't run on PRs
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Compile with NPM
        run: | 
          npm ci
          npm run all

  test-load-from-user: # test the action for the user space
    runs-on: ubuntu-latest
    concurrency: single-run
    #if: github.ref == 'refs/heads/main' # don't run on PRs
    steps: 
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      # make sure we have a new build, in case the dist folder was not updated
      - name: Compile with NPM
        run: | 
          npm ci
          npm run all

      # run the test
      - uses: ./
        name: Load used actions
        with: 
          PAT: ${{ secrets.PAT }} 
          user: rajbos
        id: load-actions      

      # check if the result file is not empty
      - name: Check if the result file is not empty
        run: | 
          if [ ! -s ${{ steps.load-actions.outputs.actions-file-path }} ]; then
            echo "The result file is empty"
            exit 1
          fi
        
      - name: Upload result file as artefact
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with: 
          name: actions-user
          path: ${{ steps.load-actions.outputs.actions-file-path }}
  
  test-load-from-organization: # test the action for the organization space
    runs-on: ubuntu-latest
    concurrency: single-run
    #if: github.ref == 'refs/heads/main' # don't run on PRs
    steps: 
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      # make sure we have a new build, in case the dist folder was not updated
      - name: Compile with NPM
        run: | 
          npm ci
          npm run all
      # run the test
      - uses: ./
        name: Load used actions
        with: 
          PAT: ${{ secrets.PAT }}
          organization: rajbos-actions
        id: load-actions

      # check if the result file is not empty
      - name: Check if the result file is not empty
        run: | 
          if [ ! -s ${{ steps.load-actions.outputs.actions-file-path }} ]; then
            echo "The result file is empty"
            exit 1
          fi
            
      - name: Upload result file as artefact
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with: 
          name: actions-organization
          path: ${{ steps.load-actions.outputs.actions-file-path }}
