name: Testing the action

on: 
  push:

  workflow_dispatch:

# Declare default GITHUB_TOKEN permissions as read only.
permissions: read-all
    
jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
      - name: Compile with NPM
        run: | 
          npm ci
          npm run all

  test-load-from-user: # test the action for the user space
    runs-on: ubuntu-latest
    concurrency: single-run
    #if: github.ref == 'refs/heads/main' # don't run on PRs
    steps: 
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
      # make sure we have a new build, in case the dist folder was not updated
      - name: Compile with NPM
        run: | 
          npm ci
          npm run all

      # run the test
      - uses: ./
        name: Load used actions
        with: 
          PAT: ${{ secrets.PAT }} 
          user: rajbos
        id: load-actions

      - uses: devops-actions/json-to-file@5984382751b07b0575aff49fe6717a021780ad07 # v1.0.0
        with: 
          json: ${{ steps.load-actions.outputs.actions }}
          filename: actions-user.json
        
      - name: Upload result file as artefact
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb # v3.1.1
        with: 
          name: actions
          path: actions-user.json
  
  test-load-from-organization: # test the action for the organization space
    runs-on: ubuntu-latest
    concurrency: single-run
    #if: github.ref == 'refs/heads/main' # don't run on PRs
    steps: 
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
      # make sure we have a new build, in case the dist folder was not updated
      - name: Compile with NPM
        run: | 
          npm ci
          npm run all
      # run the test
      - uses: ./
        name: Load used actions
        with: 
          PAT: ${{ secrets.PAT }}
          organization: rajbos-actions
        id: load-actions

      - uses: devops-actions/json-to-file@5984382751b07b0575aff49fe6717a021780ad07 # v1.0.0
        with: 
          json: ${{ steps.load-actions.outputs.actions }}
          filename: actions-organization.json
            
      - name: Upload result file as artefact
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb # v3.1.1
        with: 
          name: actions-organization
          path: actions-organization.json
